Repository myspecialway/my-special-way-portal, pull requests merged in 2018-12, with the labels that each got.

#440 Updated login page with school logo and Tinti!
  src/app/pages/login/login.component.html
  src/app/pages/login/login.component.scss
  src/assets/img/Tinti.png
  src/assets/img/school-logo.png
Labels: review

#445 Fix sort by class for students and users
  src/app/pages/student/student.component.spec.ts
  src/app/pages/student/student.component.ts
  src/app/pages/user/user.component.spec.ts
  src/app/pages/user/user.component.ts
  src/mocks/assets/students.mock.ts
Labels: review

#439 #429_reset_apollo_cache_on_logout
  src/app/services/authentication/authentication.service.spec.ts
  src/app/services/authentication/authentication.service.ts
Labels: review

#438 moved edit row from action on hover row to be clickable on row. accor…
  src/app/pages/lesson/lesson.component.html
Labels: review

#437 updated update schedule buttons to match waffle screen.
  src/app/components/schedule/schedule-dialog/schedule-dialog.html
  src/app/components/schedule/schedule-dialog/schedule-dialog.scss
Labels: review

#414 #64 admin restore password portal
  src/app/app.module.ts
  src/app/pages/user/__snapshots__/user.component.spec.ts.snap
  src/app/pages/user/dialogs/restore/error/restore-error.dialog.html
  src/app/pages/user/dialogs/restore/error/restore-error.dialog.scss
  src/app/pages/user/dialogs/restore/error/restore-error.dialog.ts
  src/app/pages/user/dialogs/restore/success/restore.dialog.html
  src/app/pages/user/dialogs/restore/success/restore.dialog.scss
  src/app/pages/user/dialogs/restore/success/restore.dialog.ts
  src/app/pages/user/user.component.html
  src/app/pages/user/user.component.spec.ts
  src/app/pages/user/user.component.ts
  src/app/services/authentication/authentication.service.spec.ts
  src/app/services/authentication/authentication.service.ts
  src/environments/environment.interface.ts
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: review

#449 Student ui
  src/app/__snapshots__/app.component.spec.ts.snap
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/components/navbar/__snapshots__/navbar.component.spec.ts.snap
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.scss
  src/app/components/schedule/schedule.component.scss
  src/app/pages/lesson/dialogs/new-edit/edit-lesson.dialog.scss
  src/app/pages/login/login.component.html
  src/app/pages/login/login.component.scss
  src/app/pages/student/details/student-details.component.scss
  src/app/pages/student/details/tabs/student-details-personal-info/__snapshots__/student-details-personal-info.component.spec.ts.snap
  src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
  src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.scss
  src/app/pages/student/dialogs/reminders/add/add-student-reminder.dialog.scss
  src/app/pages/user/dialogs/add/add-user.dialog.scss
  src/app/pages/user/dialogs/base/user-details-form/user-details-form.scss
  src/app/pages/user/dialogs/update/update-user.dialog.scss
  src/assets/icon/female.svg
  src/assets/icon/male.svg
  src/assets/img/myway.png
  src/assets/img/picking.tinti.png
  src/assets/img/tinti.png
  src/assets/scss/core/_footers.scss
  src/assets/scss/core/variables/_bootstrap-material-design.scss
  src/assets/scss/core/variables/_brand.scss
  src/assets/scss/core/variables/_colors.scss
  src/assets/scss/dialogs.scss
  src/assets/scss/msw-table.scss
Labels: review

#450 add favicon
  src/assets/img/favicon.png
Labels: review

#453 Bugfix/#452 reminders multiday toggle sync
  src/app/pages/student/dialogs/reminders/add/add-student-reminder.dialog.ts
Labels: review

#456 add 4 symbols
  src/assets/MSW Symbols/01354.png
  src/assets/MSW Symbols/animal room large.png
  src/assets/MSW Symbols/animal room small.png
  src/assets/MSW Symbols/small room by new playgroud.png
Labels: review

#473 #426 New student gets wrong User or password assigned as default
  src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
Labels: FrontEnd, bug, review

#467 #275 - bugfix/Cannot delete a class with no students
  src/app/pages/student/services/student.service.ts
Labels: bug, review

#451 Feature/non active time fonrtend#195
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/navbar/navbar.component.ts
  src/app/models/non-active-time-classes-data.model.ts
  src/app/models/non-active-time.model.ts
  src/app/pages/non-active-time/__snapshots__/non-active-time.component.spec.ts.snap
  src/app/pages/non-active-time/delete/delete-non-active-time-dialogue.component.html
  src/app/pages/non-active-time/delete/delete-non-active-time-dialogue.component.scss
  src/app/pages/non-active-time/delete/delete-non-active-time-dialogue.component.ts
  src/app/pages/non-active-time/non-active-time.component.html
  src/app/pages/non-active-time/non-active-time.component.scss
  src/app/pages/non-active-time/non-active-time.component.spec.ts
  src/app/pages/non-active-time/non-active-time.component.ts
  src/app/pages/pages.module.ts
  src/app/services/non-active-time/non-active-time.graphql.service.ts
  tests/pageobjects/navbar.po.ts
Labels: FrontEnd, review

#475 #443 edit non active time
  package.json
  src/app/app.module.ts
  src/app/pages/non-active-time/__snapshots__/non-active-time.component.spec.ts.snap
  src/app/pages/non-active-time/delete/delete-non-active-time-dialogue.component.scss
  src/app/pages/non-active-time/dialogs/delete/delete-non-active-time-dialogue.component.html
  src/app/pages/non-active-time/dialogs/delete/delete-non-active-time-dialogue.component.ts
  src/app/pages/non-active-time/dialogs/edit/__snapshots__/edit-non-active-time.dialog.spec.ts.snap
  src/app/pages/non-active-time/dialogs/edit/edit-non-active-time.dialog.html
  src/app/pages/non-active-time/dialogs/edit/edit-non-active-time.dialog.scss
  src/app/pages/non-active-time/dialogs/edit/edit-non-active-time.dialog.spec.ts
  src/app/pages/non-active-time/dialogs/edit/edit-non-active-time.dialog.ts
  src/app/pages/non-active-time/non-active-time.component.html
  src/app/pages/non-active-time/non-active-time.component.spec.ts
  src/app/pages/non-active-time/non-active-time.component.ts
  src/app/services/non-active-time/non-active-time.graphql.service.ts
  src/app/utils/hours.utils.spec.ts
  src/app/utils/hours.utils.ts
  src/app/validators/hour-validator/HourValidator.spec.ts
  src/app/validators/hour-validator/HourValidator.ts
  src/assets/scss/core/_forms.scss
  src/assets/scss/core/_radios.scss
  src/assets/scss/core/variables/_colors.scss
  src/mocks/assets/classes.mock.ts
  src/mocks/assets/nonActiveTime.mock.ts
  yarn.lock
Labels: review

#463 Ui.fixes
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/pages/student/details/tabs/student-details-personal-info/__snapshots__/student-details-personal-info.component.spec.ts.snap
  src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
  src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.scss
  src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.spec.ts
  src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.ts
  src/app/pages/user/dialogs/restore/error/restore-error.dialog.html
  src/app/pages/user/dialogs/restore/error/restore-error.dialog.scss
  src/app/pages/user/dialogs/restore/success/restore.dialog.html
  src/app/pages/user/dialogs/restore/success/restore.dialog.scss
  src/app/pages/user/user.component.ts
  src/assets/icon/female.svg
  src/assets/icon/female_disabled.svg
  src/assets/icon/female_enabled.svg
  src/assets/icon/male.svg
  src/assets/icon/male_disabled.svg
  src/assets/icon/male_enabled.svg
  src/assets/img/email.sent.png
Labels: review

#478 fix_non_active_time_table_date_header
  src/app/pages/non-active-time/non-active-time.component.html
Labels: review

#483 #465 - Prevent adding the same class twice to the DB.
  src/app/pages/class-details/class-details.container/__snapshots__/class-details.container.component.spec.ts.snap
  src/app/pages/class-details/class-details.container/class-details.container.component.spec.ts
  src/app/pages/class-details/class-details.container/class-details.container.component.ts
  src/app/pages/class/services/class.graphql.service.ts
Labels: FrontEnd, bug, review

#485 add_error_logs_to_import_student_file_validations
  src/app/file-import/students-file-import/students-file-import.service.ts
Labels: review

#409 #406 create new class titledisplays student
  src/app/components/navbar/navbar.component.spec.ts
  src/app/components/navbar/navbar.component.ts
Labels: bug, review

#497 Bugfix/#496 reminders bug
  src/app/models/reminder-time.model.ts
  src/app/models/reminder.model.ts
  src/app/pages/student/dialogs/reminders/add/add-student-reminder.dialog.html
  src/app/pages/student/dialogs/reminders/add/add-student-reminder.dialog.ts
  src/app/pages/student/dialogs/reminders/reminders.utils.spec.ts
  src/app/pages/student/dialogs/reminders/reminders.utils.ts
Labels: review

#494 delete time slot from class schedule
  src/app/app.module.ts
  src/app/components/schedule/__snapshots__/schedule.component.spec.ts.snap
  src/app/components/schedule/delete-schedule-dialog/delete-time-slot.dialog.html
  src/app/components/schedule/delete-schedule-dialog/delete-time-slot.dialog.scss
  src/app/components/schedule/delete-schedule-dialog/delete-time-slot.dialog.ts
  src/app/components/schedule/schedule.component.html
  src/app/components/schedule/schedule.component.scss
  src/app/components/schedule/schedule.component.spec.ts
  src/app/components/schedule/schedule.component.ts
  src/app/pages/class-details/class-details.container/class-details.container.component.spec.ts
  src/app/pages/class-details/class-details.container/class-details.container.component.ts
  src/app/pages/class-details/class-details.view/__snapshots__/class-details.view.component.spec.ts.snap
  src/app/pages/class-details/class-details.view/class-details.view.component.html
  src/app/pages/class-details/class-details.view/class-details.view.component.ts
  src/app/pages/class/services/class.graphql.service.ts
  src/app/pages/class/services/class.graphql.ts
Labels: review

#498 #464 logout error 401
  src/app/components/navbar/__snapshots__/navbar.component.spec.ts.snap
  src/app/components/navbar/navbar.component.ts
  src/app/pages/user/user.component.ts
  src/app/services/authentication/authentication.service.spec.ts
  src/app/services/authentication/authentication.service.ts
Labels: review

#431 #430 e2e test fixes login and students
  tests/login.e2e.ts
  tests/pageobjects/login.po.ts
  tests/pageobjects/students.po.ts
  tests/students.e2e.ts
Labels: review

#492 #472 - Console errors when updating a lesson for a student.
  src/app/components/schedule/schedule.component.ts
  src/app/pages/student/details/student-details.component.html
  src/app/pages/student/details/tabs/student-details-hours/student-details-hours.component.spec.ts
  src/app/pages/student/details/tabs/student-details-hours/student-details-hours.component.ts
  src/assets/scss/core/mixins/_buttons.scss
  src/assets/scss/msw-theme.scss
Labels: FrontEnd, bug, review

#505 #486_Maps-when_show_map_of_floor_2_cannot_select_floor_-1
  src/app/pages/maps/maps.view/map.view.component.scss
Labels: FrontEnd, bug, review

#504 #490 - Corrected validators handling in user details dialogue.
  src/app/pages/user/dialogs/base/user-details-form/user-details-form.ts
Labels: FrontEnd, bug, review

#516 #387 blocked sections
  package.json
  src/app/app.module.ts
  src/app/components/navbar/__snapshots__/navbar.component.spec.ts.snap
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
  src/app/components/spinner/spinner.component.ts
  src/app/models/responses/delete-blocked-section-response.model.ts
  src/app/pages/maps/maps.container/__snapshots__/maps.container.component.spec.ts.snap
  src/app/pages/maps/maps.container/dialogs/add-map/__snapshots__/add-map.dialog.spec.ts.snap
  src/app/pages/maps/maps.container/dialogs/add-map/add-map.dialog.html
  src/app/pages/maps/maps.container/dialogs/add-map/add-map.dialog.scss
  src/app/pages/maps/maps.container/dialogs/add-map/add-map.dialog.spec.ts
  src/app/pages/maps/maps.container/dialogs/add-map/add-map.dialog.ts
  src/app/pages/maps/maps.container/dialogs/add-update/add-update-block.dialog.html
  src/app/pages/maps/maps.container/dialogs/delete/delete-block.dialog.html
  src/app/pages/maps/maps.container/dialogs/delete/delete-block.dialog.ts
  src/app/pages/maps/maps.container/maps.container.component.spec.ts
  src/app/pages/maps/maps.container/maps.container.component.ts
  src/app/pages/maps/maps.container/maps.container.html
  src/app/pages/maps/maps.container/maps.container.scss
  src/app/pages/maps/maps.container/services/maps.container.service.spec.ts
  src/app/pages/maps/maps.container/services/maps.container.service.ts
  src/app/services/authentication/authentication.service.ts
  src/assets/scss/core/mixins/_buttons.scss
  src/assets/scss/msw-theme.scss
  src/environments/environment.interface.ts
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  tests/maps.e2e.ts
  tests/pageobjects/maps.po.ts
  tests/uploads/1.jpg
  yarn.lock
Labels: review

#517 #510 - Implemented deleting of a customized lesson from a student sch…
  src/app/pages/student/details/tabs/student-details-hours/student-details-hours.component.html
  src/app/pages/student/details/tabs/student-details-hours/student-details-hours.component.spec.ts
  src/app/pages/student/details/tabs/student-details-hours/student-details-hours.component.ts
Labels: FrontEnd, bug, review

#525 #523 - Fetching all classes and all students after a lesson has been
  src/app/services/lesson/lesson.graphql.service.ts
Labels: FrontEnd, bug, review

#527 Feature/#526 map points update locations model
  src/app/components/schedule/schedule-dialog/schedule-dialog.spec.ts
  src/app/models/location.model.ts
  src/app/models/point.model.ts
  src/app/pages/class-details/class-details.container/__snapshots__/class-details.container.component.spec.ts.snap
  src/app/pages/class-details/class-details.container/class-details.container.component.spec.ts
  src/app/pages/class/services/class.graphql.ts
  src/app/pages/maps/maps.container/tabs/map-floor-list/map-floor-list.component.spec.ts
  src/app/pages/maps/maps.container/tabs/map-points/maps-points.view/map-points.view.component.spec.ts
  src/app/pages/student/details/tabs/student-details-hours/student-details-hours.component.spec.ts
  src/app/pages/student/services/student.graphql.service.ts
  src/app/pages/student/services/student.graphql.ts
  src/app/services/location/location.graphql.service.ts
  src/mocks/assets/locations.mock.ts
Labels: review

#524 #521 - Classes are sorted in user-details dialogue box
  src/app/pages/user/dialogs/base/user-details-form/user-details-form.ts
Labels: FrontEnd, bug, review

#503 Add map
  package.json
Labels: review

#447 #261 settings page
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/navbar/navbar.component.ts
  src/app/models/settings.mode.ts
  src/app/pages/settings/__snapshots__/settings.component.spec.ts.snap
  src/app/pages/settings/services/settings.graphql.ts
  src/app/pages/settings/services/settings.service.spec.ts
  src/app/pages/settings/services/settings.service.ts
  src/app/pages/settings/settings.component.html
  src/app/pages/settings/settings.component.scss
  src/app/pages/settings/settings.component.spec.ts
  src/app/pages/settings/settings.component.ts
  src/mocks/assets/settings.mock.ts
Labels: review

#536 [000000] Adding simple instructions to environments setup.
  README.md
  simple-setup.md
Labels: review

#538 #519 Fixing text overflow issue in 'non active time' table 'reason' row…
  src/app/pages/non-active-time/non-active-time.component.html
  src/app/pages/non-active-time/non-active-time.component.scss
Labels: review

#537 #512 missing student name
  src/app/pages/student/details/tabs/student-details-hours/__snapshots__/student-details-hours.component.spec.ts.snap
  src/app/pages/student/details/tabs/student-details-hours/student-details-hours.component.html
  src/app/pages/student/details/tabs/student-details-hours/student-details-hours.component.scss
  src/app/pages/student/details/tabs/student-details-hours/student-details-hours.component.spec.ts
  src/app/pages/student/details/tabs/student-details-hours/student-details-hours.component.ts
  src/app/pages/student/details/tabs/student-details-reminders/__snapshots__/student-details-reminders.component.spec.ts.snap
  src/app/pages/student/details/tabs/student-details-reminders/student-details-reminders.component.html
  src/app/pages/student/details/tabs/student-details-reminders/student-details-reminders.component.scss
  src/app/pages/student/details/tabs/student-details-reminders/student-details-reminders.component.ts
Labels: review

#539 [535] allow to create only different blocked section Reviewer: NA
  src/app/pages/maps/maps.container/__snapshots__/maps.container.component.spec.ts.snap
  src/app/pages/maps/maps.container/maps.container.component.spec.ts
  src/app/pages/maps/maps.container/maps.container.component.ts
Labels: review

#534 #471 - Footer is displayed according to content.
  src/assets/scss/core/_footers.scss
Labels: FrontEnd, bug, review

#544 [520] Web portal - Non-active hours - - title of page displayed incor…
  src/app/pages/non-active-time/non-active-time.component.scss
Labels: review

#546 [511] Managed Maps - Text cut off Reviewer: NA
  src/app/pages/maps/maps.container/maps.container.scss
  src/app/pages/maps/maps.container/tabs/map-points/maps-points.view/map-points.view.component.scss
Labels: review

#540 first-login UI updates
  src/app/pages/firstlogin/firstlogin.component.html
  src/app/pages/firstlogin/firstlogin.component.scss
  src/app/pages/lesson/dialogs/new-edit/edit-lesson.dialog.scss
  src/app/pages/login/login.component.html
  src/app/pages/maps/maps.container/maps.container.html
  src/app/pages/maps/maps.container/maps.container.scss
  src/app/pages/shared/session-mgmt/session-footer/session-footer.component.html
  src/app/pages/shared/session-mgmt/session-footer/session-footer.component.scss
  src/app/pages/shared/session-mgmt/session-header/session-header.component.html
  src/app/pages/shared/session-mgmt/session-header/session-header.component.scss
Labels: review

#545 #484 - When the logged on used has only one class (user is a teacher)
  src/app/pages/student/details/tabs/student-details-personal-info/__snapshots__/student-details-personal-info.component.spec.ts.snap
  src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
  src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.spec.ts
  src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.ts
Labels: FrontEnd, bug, review

#550 Feature/maps/#533 add map points delete
  src/app/pages/maps/maps.container/tabs/map-points/map-points.component.ts
  src/app/services/location/location.graphql.service.ts
Labels: review

#543 #499 - Fixed time range format, which also fixed the validator
  src/app/pages/non-active-time/dialogs/edit/edit-non-active-time.dialog.ts
Labels: FrontEnd, bug, review

#552 Feature/maps/bugfix/#551 map points add functionality
  src/app/pages/maps/maps.container/tabs/map-points/map-points.component.spec.ts
  src/app/pages/maps/maps.container/tabs/map-points/map-points.component.ts
  src/app/services/location/location.graphql.service.ts
Labels: review

#557 #415 restore password link
  schema.graphql
  src/app/pages/user/dialogs/restore/error/restore-error.dialog.ts
  src/app/pages/user/services/user.graphql.ts
  src/app/pages/user/user.component.ts
  src/app/services/authentication/authentication.service.spec.ts
  src/app/services/authentication/authentication.service.ts
Labels: review

#556 Feature/maps/hotfix/#555 map points added to floor 0 always by mistake
  src/app/pages/maps/maps.container/dialogs/delete/delete-block.dialog.html
  src/app/pages/maps/maps.container/dialogs/delete/delete-block.dialog.ts
  src/app/pages/maps/maps.container/maps.container.component.ts
  src/app/pages/maps/maps.container/tabs/map-points/map-points.component.ts
  src/app/pages/maps/maps.container/tabs/map-points/maps-points.view/map-points.view.component.scss
  src/app/pages/maps/maps.container/tabs/map-points/maps-points.view/map-points.view.component.ts
Labels: review

#558 #482 create new student
  src/app/pages/student/details/student-details.component.html
  src/app/pages/student/details/student-details.component.spec.ts
  src/app/pages/student/details/student-details.component.ts
  src/app/pages/student/details/tabs/student-details-personal-info/__snapshots__/student-details-personal-info.component.spec.ts.snap
  src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.spec.ts
  src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.ts
Labels: review

#559 [547] sort the list of classes in non active Reviewer: NA
  src/app/pages/non-active-time/dialogs/edit/edit-non-active-time.dialog.ts
Labels: review

#560 Layout Fixes
  src/app/pages/student/__snapshots__/student.component.spec.ts.snap
  src/app/pages/student/details/__snapshots__/student-details.component.spec.ts.snap
  src/app/pages/student/details/student-details.component.html
  src/app/pages/student/details/student-details.component.scss
  src/app/pages/student/student.component.html
  src/assets/scss/core/_footers.scss
Labels: review

#561 [000000] Fixing the layouts. Stage 3. Maps Managment Page. Reviewer: …
  src/app/pages/maps/maps.container/maps.container.component.scss
  src/app/pages/maps/maps.container/tabs/map-points/maps-points.view/map-points.view.component.scss
Labels: review
